--- #YAML:1.0
name:               cpanauthor
version:            1.01
abstract:           print to stdout url to download link to AUTHOR DISTRO latest version
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Std::Strict:  1.01
    LEOCHARRE::Strings:   1.01
    Test::Simple:         0
    YAML:                 0.70
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
